function createfigure(cdata1)
%CREATEFIGURE(cdata1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 21-Aug-2021 16:16:03

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 12.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 12.5]);
box(axes1,'on');
axis(axes1,'ij');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',35,'Layer','top');
% Create colorbar
colorbar(axes1);

